import { TEST_URL } from './verification-config.mjs';
import { createRequire } from 'node:module';
import path from 'node:path';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const require = createRequire(path.join(process.argv[2], 'package.json'));
const { chromium } = require('playwright');
const browser = await chromium.launch({ headless: true, channel: 'msedge' });
const key = 'system-sandbox:first-level:v2', recoveryKey = 'system-sandbox:first-level:recovery';
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce', acceptDownloads: true });
  const page = await context.newPage(), errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto(`${TEST_URL}/#system-lab`);
  await page.getByRole('button', { name: 'Let’s build a link' }).click();
  await page.getByRole('button', { name: 'Add API server', exact: true }).click();
  const open = () => page.getByRole('button', { name: 'Save backups & restore' }).click();
  const close = () => page.getByRole('button', { name: 'Close save backups' }).click();
  await open();
  const downloadEvent = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download current save' }).click();
  const download = await downloadEvent, original = JSON.parse(await readFile(await download.path(), 'utf8'));
  assert.equal(original.format, 'system-sandbox-level1');
  assert.equal(original.save.design.nodes.length, 2);
  await close();
  await page.getByRole('button', { name: 'Add Database', exact: true }).click();
  await open();
  const file = page.getByLabel('Choose a Level 1 backup');
  const upload = text => file.setInputFiles({ name: 'backup.json', mimeType: 'application/json', buffer: Buffer.from(text) });
  await upload('{bad');
  await page.getByRole('status').filter({ hasText: 'Could not read this JSON' }).waitFor();
  assert.equal(await page.getByRole('button', { name: 'Restore this backup' }).count(), 0);
  await upload(JSON.stringify(original));
  await page.getByRole('heading', { name: 'Backup preview' }).waitFor();
  assert.equal(await page.evaluate(key => JSON.parse(localStorage.getItem(key)).design.nodes.length, key), 3);
  await page.getByRole('button', { name: 'Keep current board' }).click();
  assert.equal(await page.getByRole('button', { name: 'Restore this backup' }).count(), 0);
  await upload(JSON.stringify(original));
  await page.getByRole('button', { name: 'Restore this backup' }).click();
  await page.waitForFunction(key => JSON.parse(localStorage.getItem(key)).design.nodes.length === 2, key);
  assert.equal(await page.evaluate(key => JSON.parse(localStorage.getItem(key)).design.nodes.length, recoveryKey), 3);
  await page.getByRole('button', { name: 'Review recovery copy' }).click();
  await page.getByRole('button', { name: 'Restore this backup' }).click();
  await page.waitForFunction(key => JSON.parse(localStorage.getItem(key)).design.nodes.length === 3, key);
  await close();
  assert.equal(await page.getByRole('button', { name: 'Save backups & restore' }).evaluate(el => el === document.activeElement), true);
  await page.reload();
  assert.ok(await page.getByRole('button', { name: 'Inspect Database', exact: true }).isVisible());
  await page.evaluate(key => localStorage.setItem(key, '{corrupt'), key);
  await page.goto(`${TEST_URL}/`);
  await page.getByRole('status').filter({ hasText: 'recovery copy' }).waitFor();
  await page.goto(`${TEST_URL}/#system-lab`);
  assert.ok(await page.getByRole('button', { name: 'Inspect API server', exact: true }).isVisible());
  assert.equal(await page.getByRole('button', { name: 'Inspect Database', exact: true }).count(), 0);
  assert.deepEqual(errors, []);
  console.log('Save backup QA passed: download, invalid file, preview, cancel, restore, recovery, reload, campaign fallback and focus restoration.');
} finally { await browser.close(); }
