import { createRequire } from 'node:module';
import path from 'node:path';
import assert from 'node:assert/strict';
const require = createRequire(path.join(process.argv[2], 'package.json'));
const { chromium } = require('playwright');
const browser = await chromium.launch({ headless: true, channel: 'msedge' });
const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, reducedMotion: 'reduce' });
const page = await context.newPage();
const errors = [];
page.on('pageerror', e => errors.push(e.message));
await page.goto('http://127.0.0.1:5173/#system-lab');
await page.getByRole('button', { name: 'Let’s build a link' }).click();
await page.getByRole('button', { name: 'Add API server', exact: true }).click();
const api = page.getByRole('button', { name: 'Inspect API server', exact: true });
const before = await api.boundingBox();
await page.mouse.move(before.x + 50, before.y + 30);
await page.mouse.down();
await page.mouse.move(before.x + 80, before.y + 75, { steps: 5 });
await page.mouse.up();
const moved = await api.boundingBox();
assert.ok(moved.x - before.x > 25 && moved.y - before.y > 40, 'whole component drags');
await page.getByRole('button', { name: 'Undo last edit' }).click();
assert.ok(Math.abs((await api.boundingBox()).x - before.x) < 2);
await api.focus();
await page.keyboard.press('ArrowRight');
assert.ok((await api.boundingBox()).x > before.x + 10);
await page.getByRole('button', { name: 'Undo last edit' }).click();
await api.click();
await page.getByRole('button', { name: 'How this component works' }).click();
await page.getByRole('dialog').waitFor();
await page.keyboard.press('Escape');
assert.equal(await page.getByRole('dialog').count(), 0);
await page.getByRole('button', { name: 'Add Database', exact: true }).click();
await page.getByRole('button', { name: 'Start call from Visitors', exact: true }).click();
await page.getByRole('button', { name: 'Connect to API server', exact: true }).click();
await page.getByRole('button', { name: 'Start call from API server', exact: true }).click();
await page.getByRole('button', { name: 'Connect to Database', exact: true }).click();
await page.getByRole('button', { name: 'Inspect connection from API server to Database' }).click();
await page.getByRole('button', { name: 'Disconnect call' }).click();
await page.getByRole('button', { name: 'Send traffic', exact: true }).click();
assert.ok(await page.getByRole('alert').isVisible());
await page.getByRole('button', { name: 'Undo last edit' }).click();
await page.getByRole('button', { name: 'Send traffic', exact: true }).click();
await page.getByText('CHALLENGE PASSED', { exact: true }).waitFor({ timeout: 18000 });
await page.screenshot({ path: 'artifacts/first-level-desktop-final.png', fullPage: true });
await page.setViewportSize({ width: 1024, height: 768 });
await page.screenshot({ path: 'artifacts/first-level-tablet-final.png', fullPage: true });
const layout = await page.locator('.l1-layout').boundingBox();
const workbench = await page.locator('.l1-workbench').boundingBox();
assert.ok(workbench.y + workbench.height <= layout.y + layout.height, 'workbench is not clipped');
await page.setViewportSize({ width: 390, height: 844 });
await page.screenshot({ path: 'artifacts/first-level-mobile-final.png', fullPage: true });
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
await page.getByRole('button', { name: 'Try again', exact: true }).scrollIntoViewIfNeeded();
const button = await page.getByRole('button', { name: 'Try again', exact: true }).boundingBox();
assert.ok(button.y >= 0 && button.y < 844, 'mobile controls are reachable');
assert.deepEqual(errors, []);
console.log('Editor QA passed: pointer drag, keyboard move, undo, guide focus/escape, disconnect/validation, traffic success, tablet workbench, mobile scroll and controls.');
await browser.close();
