// Usage: node scripts/verify-level.mjs <directory containing playwright>
// Browser checks use an isolated context and never touch the player's saved board.
import { createRequire } from 'node:module';
import path from 'node:path';
import { mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
const require = createRequire(path.join(process.argv[2], 'package.json'));
const { chromium } = require('playwright');
const artifactDir = path.resolve(process.argv[3] || 'artifacts');
await mkdir(artifactDir, { recursive: true });
const browser = await chromium.launch({ headless: true, channel: 'msedge' });
try {
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
const page = await context.newPage();
const errors = [];
page.on('pageerror', error => errors.push(error.message));
await page.goto('http://127.0.0.1:5173/#system-lab');
await page.getByRole('button', { name: 'Let’s build a link' }).click();
await page.screenshot({ path: path.join(artifactDir, 'first-level-empty.png'), fullPage: true });
await page.getByRole('button', { name: 'Add API server', exact: true }).click();
await page.getByRole('button', { name: 'Add Database', exact: true }).click();
await page.getByRole('button', { name: 'Start call from Visitors', exact: true }).click();
await page.getByRole('button', { name: 'Connect to API server', exact: true }).click();
await page.getByRole('button', { name: 'Start call from API server', exact: true }).click();
await page.getByRole('button', { name: 'Connect to Database', exact: true }).click();
await page.getByRole('button', { name: 'Follow one request' }).click();
await page.getByRole('button', { name: /Read the saved mapping/ }).click();
assert.ok(await page.getByText('SELECT destination WHERE code = bakery.', { exact: false }).isVisible());
await page.screenshot({ path: path.join(artifactDir, 'first-level-trace.png'), fullPage: true });
await page.getByRole('button', { name: 'Close request trace' }).click();
await page.getByRole('button', { name: 'Send traffic', exact: true }).click();
await page.getByRole('button', { name: 'Pause traffic' }).click();
const paused = await page.locator('.l1-system-state').innerText();
assert.ok(paused.includes('Paused'));
await page.getByRole('button', { name: 'Resume traffic' }).click();
await page.getByText('CHALLENGE PASSED', { exact: true }).waitFor({ timeout: 18000 });
await page.screenshot({ path: path.join(artifactDir, 'first-level-passed.png'), fullPage: true });
await page.getByRole('slider', { name: 'Scrub traffic test' }).fill('3');
await page.getByRole('button', { name: 'Next challenge', exact: true }).click();
await page.getByRole('button', { name: 'Send traffic', exact: true }).click();
await page.getByText('A USEFUL FAILURE', { exact: true }).waitFor({ timeout: 22000 });
await page.screenshot({ path: path.join(artifactDir, 'first-level-failure.png'), fullPage: true });
assert.ok((await page.locator('.l1-result-explanation').innerText()).includes('API server rejected'));
await page.reload();
await page.getByRole('button', { name: 'Inspect API server', exact: true }).waitFor();
assert.equal(await page.getByRole('dialog').count(), 0);
await page.getByRole('button', { name: 'Inspect API server', exact: true }).click();
await page.getByLabel('SHORT CODE STRATEGY').selectOption('random');
await page.locator('.l1-tiers').getByRole('button', { name: /Medium/ }).click();
await page.getByRole('button', { name: 'Apply Medium tier', exact: true }).click();
await page.getByRole('button', { name: 'Inspect Database', exact: true }).click();
await page.locator('.l1-tiers').getByRole('button', { name: /Medium/ }).click();
await page.getByRole('button', { name: 'Apply Medium tier', exact: true }).click();
await page.getByRole('button', { name: 'Add Memory cache', exact: true }).click();
await page.getByRole('button', { name: 'Start call from API server', exact: true }).click();
await page.getByRole('button', { name: 'Connect to Memory cache', exact: true }).click();
await page.getByRole('button', { name: 'Send traffic', exact: true }).click();
await page.getByText('CHALLENGE PASSED', { exact: true }).waitFor({ timeout: 22000 });
await page.getByRole('button', { name: 'Next challenge', exact: true }).click();
await page.getByRole('button', { name: 'Send traffic', exact: true }).click();
await page.getByText('CHALLENGE PASSED', { exact: true }).waitFor({ timeout: 22000 });
await page.screenshot({ path: path.join(artifactDir, 'first-level-final.png'), fullPage: true });
await page.getByRole('button', { name: 'Test all three', exact: true }).click();
await page.getByText('Every challenge, one design.', { exact: true }).waitFor({ timeout: 55000 });
await page.screenshot({ path: path.join(artifactDir, 'first-level-certified.png'), fullPage: true });
await page.setViewportSize({ width: 1024, height: 768 });
await page.screenshot({ path: path.join(artifactDir, 'first-level-tablet.png'), fullPage: true });
await page.setViewportSize({ width: 390, height: 844 });
await page.screenshot({ path: path.join(artifactDir, 'first-level-mobile.png'), fullPage: true });
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
assert.deepEqual(errors, []);
console.log('Browser QA passed: onboarding, graph editing, request trace, pause/resume, failure diagnosis, save/reload, alternative strategy, all challenges, full contract, mobile overflow.');
} finally { await browser.close(); }
