import { TEST_URL } from './verification-config.mjs';
import { createRequire } from 'node:module';
import path from 'node:path';
import assert from 'node:assert/strict';
const require = createRequire(path.join(process.argv[2], 'package.json'));
const { chromium } = require('playwright');
const browser = await chromium.launch({ headless: true, channel: 'msedge' });
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
  const page = await context.newPage(), errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto(`${TEST_URL}/#system-lab`);
  await page.getByRole('button', { name: 'Let’s build a link' }).click();
  const help = page.getByRole('region', { name: 'Contextual help' });
  await page.getByRole('button', { name: 'Give me a nudge' }).click();
  assert.equal(await help.locator('p').count(), 0);
  await page.getByRole('button', { name: 'Show the evidence' }).click();
  assert.ok((await help.innerText()).includes('Visitors need a connected API'));
  await page.getByRole('button', { name: 'Suggest an experiment' }).click();
  assert.ok((await help.innerText()).includes('Make one connection change'));
  assert.ok(await page.getByRole('button', { name: 'All hints shown' }).isDisabled());
  await help.getByRole('button', { name: 'Dismiss help' }).click();
  assert.equal(await help.count(), 0);
  await page.getByRole('button', { name: 'Add API server', exact: true }).click();
  await page.getByRole('button', { name: 'Add Database', exact: true }).click();
  await page.getByRole('button', { name: 'Start call from Visitors', exact: true }).click();
  await page.getByRole('button', { name: 'Connect to API server', exact: true }).click();
  await page.getByRole('button', { name: 'Start call from API server', exact: true }).click();
  await page.getByRole('button', { name: 'Connect to Database', exact: true }).click();
  await page.getByRole('button', { name: 'Inspect API server', exact: true }).click();
  await page.getByLabel('SHORT CODE STRATEGY').selectOption('service');
  await page.getByRole('button', { name: 'Give me a nudge' }).click();
  await page.getByRole('button', { name: 'Show the evidence' }).click();
  await page.getByRole('button', { name: 'Suggest an experiment' }).click();
  assert.ok((await help.innerText()).includes('database sequence / random codes'));
  await page.getByLabel('SHORT CODE STRATEGY').selectOption('random');
  assert.equal(await help.count(), 0);
  await page.getByRole('button', { name: 'Give me a nudge' }).click();
  await page.getByRole('button', { name: 'Show the evidence' }).click();
  assert.ok((await help.innerText()).includes('functional checks pass'));
  await help.getByRole('button', { name: 'Inspect the evidence' }).click();
  assert.ok(await page.getByRole('heading', { name: 'API server', exact: true }).isVisible());
  assert.deepEqual(errors, []);
  console.log('Contextual help QA passed: opt-in stages, no cycling, dismiss, state change, missing-service alternatives and evidence focus.');
} finally { await browser.close(); }
